### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by domin-mnd** [domin-mnd/shakespeare#1]
> **Note** Will be linking pull requests to this issue.

- Frontend
  - [ ] Layout - Minimal UI, no overwhelming mock ups & huge TODOs
  - [ ] UI Library - Reuseful components for inner/outer layouts
  - [ ] Setup styling - Less / Stylus space, font, rounding, color systems, may be inherited from other projects
  - [ ] JSDocs - Page & Utility documentation
  - [ ] Landing page - Small upload page
  - [ ] Static data fetching - APIs for internal data
  - [ ] Meta tags - Dynamic open graph & twitter tags
  - [ ] Media layout - Custom inner media layout inherited from minimal UI of outer layout
  - [ ] Dashboard page - Management panel for user & configuration purposes
- Backend
  - [ ] API - Basics of ShareX REST + additional features
  - [ ] Minifiers - Consider on adding minifiers to media load times
  - [ ] Database - Setup Prisma for analytics & users
  - [ ] Storage - Should be a middleware to S3 for additional use case
  - [ ] Deployment - Should be considered a compatibility check
  - [ ] Unit testing - Either [Jest](https://jestjs.io/) or [Mocha](https://mochajs.org/)
  - [ ] Security - [Lucia](https://lucia-auth.com) or [Clerk](https://clerk.com/) for auth, environment variables over object notation files
  - [ ] JSDocs - Explain every service & controller
  - [ ] Documentation - OpenAPI specification additional modification to ShareX docs
  - [ ] Boilerplate guides - additional content for different IaaS, PaaS, Web Hosting setups
  - [ ] Performance overload - final stage of release

**Comment by domin-mnd** [comment]
As of 9th june, for backend there are not much things left: analytics endpoints, lib jsdocs, documentation

**Comment by domin-mnd** [comment]
The active work is still underway: for the given number of pages, the ui is partially done & functional register & login pages were made, right now all eyes on profile page

The way to optimize client view of uploads is being thought through. Trying to include as less javascript to client-side as possible.

Database may face polishing for the sake of correct DX in the future.

**Comment by domin-mnd** [comment]
^
Added View model to the database in order to fix view date issue, leads to breaking changes.
